/*
 * Copyright (C) 2019 Jolla Ltd.
 * Copyright (C) 2019 Slava Monich <slava@monich.com>
 *
 * You may use this file under the terms of BSD license as follows:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   1. Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer
 *      in the documentation and/or other materials provided with the
 *      distribution.
 *   3. Neither the names of the copyright holders nor the names of its
 *      contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <rpm/rpmlib.h>
#include <rpm/header.h>
#include <rpm/rpmts.h>
#include <rpm/rpmdb.h>

#include <dlfcn.h>

#define LIBRPM_FUNCTIONS(f) \
    f(rpmts, rpmtsCreate, (void), (), 0) \
    f(rpmdbMatchIterator, rpmtsInitIterator, \
     (const rpmts ts, rpmDbiTagVal rpmtag, const void * keyp, size_t keylen), \
     (ts, rpmtag, keyp, keylen), NULL) \
    f(Header, rpmdbNextIterator, (rpmdbMatchIterator mi), (mi), NULL) \
    f(const char *, headerGetString, (Header h, rpmTagVal tag), \
     (h, tag), NULL) \
    f(rpmdbMatchIterator, rpmdbFreeIterator, (rpmdbMatchIterator mi), \
     (mi), NULL) \
    f(rpmts, rpmtsFree, (rpmts ts), (ts), 0)

/*
 * We only need to determine transfer-engine version on old releases of
 * Sailfish OS, so if librpm.so.2 isn't there (and it's not there on
 * newer releases), we just assume the new plugin API and don't really
 * need to know the exact transfer-engine version (until API changes again)
 */
#define LIBRPM_SO            "/usr/lib/librpm.so.8"
#define LIBRPM_NUM_FUNCTIONS (sizeof(librpm_names)/sizeof(librpm_names[0]))
#define LIBRPM_NO_HANDLE     ((void*)-1)

static const char* librpm_names[] = {
    "rpmReadConfigFiles",
    #define FN_NAME(type,name,params,args,fail) #name,
    LIBRPM_FUNCTIONS(FN_NAME)
};

static struct {
    void* handle;
    union {
        struct librpm_proc {
            int (*rpmReadConfigFiles)(const char* file, const char* target);
            #define FN_POINTER(type,name,params,args,fail) type (* name) params;
            LIBRPM_FUNCTIONS(FN_POINTER)
        } librpm;
        void* entry[LIBRPM_NUM_FUNCTIONS];
    } fn;
} librpm;

/* rpmReadConfigFiles() is the special function where we load the library */
int rpmReadConfigFiles(const char* file, const char* target)
{
    if (!librpm.handle) {
        librpm.handle = dlopen(LIBRPM_SO, RTLD_LAZY);
        if (librpm.handle) {
            unsigned int i;
            for (i=0; i<LIBRPM_NUM_FUNCTIONS; i++) {
                librpm.fn.entry[i] = dlsym(librpm.handle, librpm_names[i]);
            }
        } else {
            librpm.handle = LIBRPM_NO_HANDLE;
        }
    }
    return librpm.fn.librpm.rpmReadConfigFiles ?
        librpm.fn.librpm.rpmReadConfigFiles(file, target) :
        -1;
}

/* All other wrappers are generated by the preprocessor */
#define FN_IMPL(type,name,params,args,fail) type name params \
  { return librpm.fn.librpm.name ? librpm.fn.librpm.name args : fail; }
LIBRPM_FUNCTIONS(FN_IMPL)
